-- liquibase formatted sql

-- changeset jakub:create-contribution_config-table
CREATE TABLE contribution_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- contribution type: 'FIXED' or 'VARIABLE' (future types can be added)
    type VARCHAR(50) NOT NULL,
    -- For FIXED: percentage is used. For VARIABLE: variable_initial_percentage and variable_decay_rate drive behavior.
    percentage NUMERIC(9,8),
    variable_initial_percentage NUMERIC(9,8),
    -- Decay rate expressed as absolute decrease in percentage in decimal fraction per initial pool.
    variable_decay_rate NUMERIC(18,12),
    min_percentage NUMERIC(9,8),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- add check constraints to ensure percentages are sane
ALTER TABLE contribution_config
    ADD CONSTRAINT chk_pct_range CHECK (percentage IS NULL OR (percentage >= 0 AND percentage <= 1));

ALTER TABLE contribution_config
    ADD CONSTRAINT chk_var_init_pct_range CHECK (variable_initial_percentage IS NULL OR (variable_initial_percentage >= 0 AND variable_initial_percentage <= 1));

ALTER TABLE contribution_config
    ADD CONSTRAINT chk_min_pct_range CHECK (min_percentage IS NULL OR (min_percentage >= 0 AND min_percentage <= 1));

ALTER TABLE contribution_config
    ADD CONSTRAINT chk_decay_non_negative CHECK (variable_decay_rate IS NULL OR variable_decay_rate >= 0);


-- changeset jakub:create-reward_config-table
CREATE TABLE reward_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- reward type: 'FIXED' or 'VARIABLE' (future types can be added)
    type VARCHAR(50) NOT NULL,
    -- For FIXED: constant chance for reward
    chance NUMERIC(9,8),
    -- For VARIABLE: chance grows from initial value to 100% as pool grows
    initial_chance NUMERIC(9,8),
    -- When pool reaches this multiple of initial pool, chance becomes 100%
    max_pool_multiplier NUMERIC(9,2),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- add check constraints to ensure chances are sane
ALTER TABLE reward_config
    ADD CONSTRAINT chk_chance_range CHECK (chance IS NULL OR (chance >= 0 AND chance <= 1));

ALTER TABLE reward_config
    ADD CONSTRAINT chk_initial_chance_range CHECK (initial_chance IS NULL OR (initial_chance >= 0 AND initial_chance <= 1));

ALTER TABLE reward_config
    ADD CONSTRAINT chk_max_pool_multiplier_positive CHECK (max_pool_multiplier IS NULL OR max_pool_multiplier >= 1);

-- changeset jakub:create-jackpot-table
CREATE TABLE jackpot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contribution_config_id BIGINT NOT NULL,
    reward_config_id BIGINT NOT NULL,
    FOREIGN KEY (contribution_config_id) REFERENCES contribution_config(id) ON DELETE RESTRICT,
    FOREIGN KEY (reward_config_id) REFERENCES reward_config(id) ON DELETE RESTRICT,
    initial_pool NUMERIC(19,2) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- changeset jakub:create-contribution-type-enum
-- @jooq-force-types=ENUM
CREATE TYPE contribution_type AS ENUM ('CONTRIBUTION', 'REWARD', 'UNREWARDED');

-- changeset jakub:create-jackpot_contribution-table
CREATE TABLE jackpot_contribution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Type distinguishing between contributions and rewards
    type contribution_type NOT NULL,
    bet_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    jackpot_id BIGINT NOT NULL,
    -- For contributions: actual bet stake amount. For rewards: 0
    stake_amount NUMERIC(19,2) NOT NULL,
    -- For contributions: positive amount added to pool
    -- For rewards: negative amount withdrawn from pool
    contribution_amount NUMERIC(19,2) NOT NULL,
    -- Pool amount after the operation, must stay positive
    jackpot_amount_after NUMERIC(19,2) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (jackpot_id) REFERENCES jackpot(id) ON DELETE RESTRICT,
    -- Ensure stake amounts are valid:
    -- - rewards: 0 stake (winning bet)
    -- - unrewarded: 0 stake (non-winning bet)
    -- - contributions: positive stake (initial bet)
    CONSTRAINT chk_stake_amount CHECK (
        (type IN ('REWARD', 'UNREWARDED') AND stake_amount = 0) OR
        (type = 'CONTRIBUTION' AND stake_amount >= 0)
    ),
    -- Ensure contribution amounts are valid:
    -- - rewards: negative (money out)
    -- - unrewarded: 0 (no money movement)
    -- - contributions: positive (money in)
    CONSTRAINT chk_contribution_amount CHECK (
        (type = 'REWARD' AND contribution_amount < 0) OR
        (type = 'UNREWARDED' AND contribution_amount = 0) OR
        (type = 'CONTRIBUTION' AND contribution_amount > 0)
    ),
    -- Pool must always stay positive
    CONSTRAINT chk_pool_positive CHECK (jackpot_amount_after >= 0)
);

-- Add composite index for efficient latest contribution/reward lookup
CREATE INDEX idx_jackpot_contribution_latest ON jackpot_contribution(jackpot_id, created_at DESC);

-- Ensure each bet can only:
-- 1. Have one contribution entry
-- 2. Have exactly one reward status (either REWARD or UNREWARDED, but not both)
CREATE UNIQUE INDEX unq_jackpot_contribution_bet_contribution ON jackpot_contribution(bet_id) WHERE type = 'CONTRIBUTION';
CREATE UNIQUE INDEX unq_jackpot_contribution_bet_reward_status ON jackpot_contribution(bet_id) WHERE type IN ('REWARD', 'UNREWARDED');
